[WIP] Fixes #10: Add Dockerfile for Yacy
yacy/yacy_grid_mcp pull request #12
Opened 2017-07-11 11:34 UTC by harshit98

Fixes #10 

In this PR: 
- Created a Dockerfile for running MCP service.
- Created a `docker-compose.yml` to link apache ftp, elasticsearch and rabbitmq containers.

Kindly review @nikhilrayaprolu @Marauderer97 @Orbiter

2017-07-11 12:02 UTC, nikhilrayaprolu requested changes

2017-07-11 12:02 UTC, nikhilrayaprolu commented on Dockerfile
> +
configure apache ftp server
**Things to do:**

1.add these lines to apache-ftpserver-1.1.0/res/conf/users.properties
```
ftpserver.user.yacygrid.userpassword=fcd6f2c8d772db634cd9fd960f4668a0
ftpserver.user.yacygrid.homedirectory=./res/home
ftpserver.user.yacygrid.enableflag=true
ftpserver.user.yacygrid.writepermission=true
ftpserver.user.yacygrid.maxloginnumber=2000
ftpserver.user.yacygrid.maxloginperip=2000
ftpserver.user.yacygrid.idletime=300
ftpserver.user.yacygrid.uploadrate=0
ftpserver.user.yacygrid.downloadrate=0
```

you can refer https://unix.stackexchange.com/questions/77277/how-to-append-multiple-lines-to-a-file for how to add multiple lines into a file.
but I prefer write these configurations into a configfile and then
do,

`cat ftpconfigfile >> apache-ftpserver-1.1.0/res/conf/users.properties`

2017-07-11 12:02 UTC, nikhilrayaprolu commented on Dockerfile
> +RUN rabbitmq_server-3.6.10/sbin/rabbitmq-plugins enable rabbitmq_management
`rabbitmq_server-3.6.6/sbin/rabbitmqctl add_user yacygrid password4account`
use the same username and password as given in the instructions

2017-07-11 12:02 UTC, nikhilrayaprolu commented on Dockerfile
> +RUN rabbitmq_server-3.6.10/sbin/rabbitmq-plugins enable rabbitmq_management
add these lines
`[{rabbit, [{loopback_users,[]}]}].` to rabbitmq_server-3.6.6/etc/rabbitmq/rabbitmq.config using `echo` command .

2017-07-11 12:02 UTC, nikhilrayaprolu commented on Dockerfile
> +RUN rabbitmq_server-3.6.10/sbin/rabbitmq-plugins enable rabbitmq_management
now configure MCP with the following lines
make a `MCPconfigfile`  file with same content as `/conf/config.properties` replace with these lines```

grid.ftp.address = yacygrid:password4account@localhost:2121
grid.broker.address = yacygrid:password4account@localhost:5672
```

2017-07-11 12:24 UTC, nikhilrayaprolu requested changes

2017-07-11 12:24 UTC, nikhilrayaprolu commented on docker-compose.yml
> +    image: elasticsearch
replace this with compose format given at https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

2017-07-11 12:24 UTC, nikhilrayaprolu commented on docker-compose.yml
> +    image: elasticsearch
also update the clustername to "yacygrid" as given in instructions

2017-07-11 15:58 UTC, harshit98 commented
@nikhilrayaprolu Kindly review.

2017-07-11 19:46 UTC, nikhilrayaprolu requested changes

2017-07-11 19:46 UTC, nikhilrayaprolu commented on Dockerfile
> +RUN echo [{rabbit, [{loopback_users, []}]}].
add this line into `rabbitmq_server-3.6.6/etc/rabbitmq/rabbitmq.config`

2017-07-11 19:46 UTC, nikhilrayaprolu commented on config-mcp.properties
> +# YaCy Grid Peer configuration
copy this configuration file to data/mcp-8100/conf/config.properties
using cp command

2017-07-11 19:48 UTC, nikhilrayaprolu requested changes

2017-07-11 19:48 UTC, nikhilrayaprolu commented on docker-compose.yml
> +  elasticsearch2:
why do we need two elasticsearch containers.

2017-07-11 19:52 UTC, nikhilrayaprolu requested changes

2017-07-11 19:52 UTC, nikhilrayaprolu commented on docker-compose.yml
> +services:
```
version: "2"
  services:
  yacy_MCP:
   name: "yacy"
   build: .
   ports:
   - "80:80"
   links:
   - elasticsearch
 

```
missing the main service

2017-07-11 19:55 UTC, harshit98 commented on docker-compose.yml
> +  elasticsearch2:
Okay I will remove second container.

2017-07-11 20:41 UTC, harshit98 commented on config-mcp.properties
> +# YaCy Grid Peer configuration
Done @nikhilrayaprolu

2017-07-12 05:53 UTC, nikhilrayaprolu requested changes
we have many files that are specifically for Docker, don't pull all these files in the root directory, create a folder named Docker and put all these files there. for instance check https://github.com/yacy/yacy_search_server

2017-07-12 07:17 UTC, Orbiter approved these changes

2017-07-12 07:20 UTC, Orbiter commented
yes looks good but please consider suggestion from @nikhilrayaprolu

2017-07-12 12:38 UTC, harshit98 commented
Done. @Orbiter @nikhilrayaprolu

2017-07-12 12:55 UTC, nikhilrayaprolu commented
@harshit98 there are alot more changes needed to be done.

2017-07-12 12:56 UTC, nikhilrayaprolu commented
I am testing my Docker on my local system will update you, once it is done.

2017-07-13 06:06 UTC, nikhilrayaprolu commented
@harshit98 you can close this pull request or update it with the changes I made at https://github.com/yacy/yacy_grid_mcp/pull/13

2017-07-13 09:01 UTC, closed without merging