Fixes #15 deploys master branch to google cloud
yacy/yacy_grid_mcp pull request #16
Opened 2017-07-16 12:51 UTC by nikhilrayaprolu

Made all changes required for the deployment and got the container working on google cloud, I have tested this on my own repo, and got it working. related travis report is at https://travis-ci.org/nikhilrayaprolu/yacy_grid_mcp .

One need admin account to add authentication keys google cloud.
![image](https://user-images.githubusercontent.com/15216503/28247707-8c988158-6a53-11e7-8d8b-b339ad5958e4.png)

2017-07-16 14:02 UTC, niranjan94 requested changes
.

2017-07-16 14:02 UTC, niranjan94 requested changes
@nikhilrayaprolu @mariobehling

2017-07-16 14:02 UTC, niranjan94 commented on deploy_staging.sh
> +gcloud docker -- push gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}
Why do we need to use google cloud's private repository hosting service ? This is anyway an open source project. So, a private container hosting doesn't make sense and we'll be paying extra for it. (Google cloud platform isn't cheap) 

We can use Docker Hub instead (https://hub.docker.com) like how we do for Open Event. 

https://hub.docker.com/u/eventyay/

2017-07-16 14:21 UTC, nikhilrayaprolu commented on deploy_staging.sh
> +gcloud docker -- push gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}
@niranjan94 as far as I know docker hub is just a docker registry and not a container service.so we could just push and test images on docker hub, but cannot deploy or host them.

2017-07-16 14:23 UTC, mariobehling commented on deploy_staging.sh
> +gcloud docker -- push gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}
Yes, public is better. I am checking if @Orbiter has access to the Yacy org on Docker. If not we need to set up another org.

2017-07-16 14:24 UTC, mariobehling commented on deploy_staging.sh
> +gcloud docker -- push gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}
@nikhilrayaprolu Please check out the flow to go through Dockerhub in the meantime.

2017-07-16 14:24 UTC, niranjan94 commented on deploy_staging.sh
> +gcloud docker -- push gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}
@nikhilrayaprolu you can host the docker images there and use them in your kubernetes configuration. A replacement for `gcr.io`. 

We have been doing that for quite sometime with eventyay. https://hub.docker.com/u/eventyay/

2017-07-16 14:28 UTC, nikhilrayaprolu commented on deploy_staging.sh
> +gcloud docker -- push gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}
@niranjan94 do you mean to replace just gcr.io for image building and run the container on hosting services like google cloud?

2017-07-16 14:37 UTC, niranjan94 commented on deploy_staging.sh
> +gcloud docker -- push gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}
@nikhilrayaprolu yes something like that ... See

- https://github.com/fossasia/open-event-orga-server/blob/nextgen/kubernetes/travis/deploy-nextgen.sh#L33
- https://github.com/fossasia/open-event-orga-server/blob/nextgen/kubernetes/yamls/api-server/api-deployment.yml#L21
- https://hub.docker.com/r/eventyay/nextgen-api-server/tags/

2017-07-16 14:37 UTC, nikhilrayaprolu commented on deploy_staging.sh
> +gcloud docker -- push gcr.io/${PROJECT_NAME_STG}/${DOCKER_IMAGE_NAME}
@niranjan94 I found these files where eventyay related repositories, where dockerhub is used for image registry and google cloud for hosting. https://github.com/fossasia/open-event-frontend/blob/development/kubernetes/travis/deploy.sh . do you mean to proceed like this?

2017-07-18 07:36 UTC, nikhilrayaprolu commented
@mariobehling I have replaced the google cloud registry with docker registry. @Orbiter I don't have permissions to add service keys and docker related keys into travis of this repository.
right now the image for yacygrid is available at https://hub.docker.com/r/nikhilrayaprolu/yacygridmcp/

2017-07-18 07:37 UTC, nikhilrayaprolu commented
I have tested deployment with my forked repo and it got passed, the related travis log is at https://travis-ci.org/nikhilrayaprolu/yacy_grid_mcp/builds/254743090?utm_source=github_status&utm_medium=notification

2017-07-18 07:52 UTC, mariobehling commented
@nikhilrayaprolu Ok, let's merge this and iterate from here.

2017-07-18 07:53 UTC, merged

2017-07-18 07:57 UTC, nikhilrayaprolu commented
@mariobehling can I get temporary access to admin rights for this repository so that I could add the keys into travis.