Modified run_all.py script to update all the components and run each component.
yacy/yacy_grid_mcp pull request #31
Opened 2018-05-07 02:15 UTC by praveenojha33

Modified run_all.py script to update all the components and run each component in a separate terminal.

2018-05-09 19:50 UTC, harshit98 approved these changes

2018-05-14 11:19 UTC, Orbiter requested changes
Why is this gnome-dependent? ("gnome-terminal") It shouldn't be.

2018-05-17 04:20 UTC, praveenojha33 commented
@Orbiter I have updated the code, Please review :smile:

2018-05-17 08:24 UTC, Orbiter approved these changes

2018-05-17 08:24 UTC, merged